version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mauna_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-mauna}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - mauna_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mauna_app
    restart: unless-stopped
    environment:
      - DATABASE_HOSTNAME=202.10.36.217
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME:-mauna}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_here}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-3600}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-True}
      - RATE_LIMIT=${RATE_LIMIT:-3600}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    volumes:
      - ./src/storage:/app/src/storage
    ports:
      - "8888:8000"  # External port 8888, internal tetap 8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mauna_network

volumes:
  postgres_data:
    driver: local

networks:
  mauna_network:
    driver: bridge

